#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Verbose mode
if [ "$1" == "-v" ]; then
	verbose=true
	echo "Verbose mode on"
fi

# Functions
function enable {
	if systemctl is-enabled --quiet $1; then
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${GREEN}Done${NC}\n"
		fi
	else
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${YELLOW}Warning $1 is not enable${NC}\n"
		fi
		sudo systemctl enable $1
	fi
}

function active {
	if systemctl is-active --quiet $1; then
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${GREEN}Done${NC}\n"
		fi
	else
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${RED}Error $1 is not active${NC}\n"
		fi
	fi
	echo -e "\tRestarting $1"
	sudo systemctl restart $1
}

# ---------------------------------------------
# INSTALLATION 
# ---------------------------------------------
# curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
# echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
# sudo apt update
# sudo apt install elasticsearch

# ---------------------------------------------
# CONFIGURATION
# ---------------------------------------------
# Si se quiere acceder desde fuera
# primero activar firewall
# sudo ufw enable
# sudo ufw allow 9200
# Solo una ip
# sudo ufw allow from 192.168.1.16 to any port 9200
# sudo ufw status numbered
#
# sudo vim /etc/elasticsearch/elasticsearch.yml
# network.host: 0.0.0.0
# http.port: 9200
# At the end of the file in Security section
# discovery.type: single-node

#----------------------------------------------
# SERVICE
#----------------------------------------------
# enable:
enable elasticsearch
# active:
active elasticsearch

# ---------------------------------------------
# TEST
# ---------------------------------------------
if [ "$1" == "-t" ]; then
	echo -e "\n${YELLOW}Testing Elasticsearch${NC}"
	curl -X GET "localhost:9200/"
	echo -e "\n${YELLOW}Testing Elasticsearch with a query${NC}"
	curl -X GET "localhost:9200/_search?q=*&pretty"
fi
