#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Verbose mode
if [ "$1" == "-v" ]; then
	verbose=true
	echo "Verbose mode on"
fi

# Functions
function enable {
	if systemctl is-enabled --quiet $1; then
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${GREEN}Done${NC}\n"
		fi
	else
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${YELLOW}Warning $1 is not enable${NC}\n"
		fi
		sudo systemctl enable $1
	fi
}

function active {
	if systemctl is-active --quiet $1; then
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${GREEN}Done${NC}\n"
		fi
	else
		if [ "$verbose" == "true" ]; then
			echo -e "\t[>] ${RED}Error $1 is not active${NC}\n"
		fi
	fi
	if sudo nginx -t -q; then 
		echo -e "\tRestarting $1"
		sudo systemctl restart $1
	fi
}

# ----------------------------------------------
# INSTALLATION 
# ----------------------------------------------
# sudo apt update
# sudo apt install nginx

# ----------------------------------------------
# CONFIGURATION FIREWALL
# ----------------------------------------------
# sudo ufw app list
# sudo ufw allow {'Nginx HTTP'||'Nginx HTTPS'||'Nginx FULL'} # most restrictive to least restrictive
# sudo ufw status

# sudo vim /etc/nginx/sites-available/elastic	-> port 999
# sudo vim /etc/nginx/sites-available/kibana 	-> port 1000

# sudo ln -s /etc/nginx/sites-available/elastic /etc/nginx/sites-enabled/
# sudo ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/

# sudo ufw allow 999 	# elasticsearch	-> Port Forwarding Int:999 Ext:999 		IP:192.168.1.30
# sudo ufw allow 1000	# kibana 		-> Port Forwarding Int:1000 Ext:1000 	IP:192.168.1.30

#----------------------------------------------
# SERVICE
#----------------------------------------------
# sudo systemctl status nginx
# sudo systemctl start nginx
# sudo systemctl stop nginx
# sudo systemctl restart nginx
# sudo systemctl reload nginx
# sudo systemctl disable nginx
# sudo systemctl enable nginx

# enable:
enable nginx
# active:
active nginx

#----------------------------------------------
# PAGES
#----------------------------------------------
# sudo mkdir -p /var/www/your_domain/html
# sudo chown -R $USER:$USER /var/www/your_domain/html
# sudo chmod -R 755 /var/www/your_domain
# vim /var/www/your_domain/html/index.html

# sudo vim /etc/nginx/sites-available/your_domain
# server {
#         listen 80;
#         listen [::]:80;
# 
#         root /var/www/your_domain/html;
#         index index.html index.htm index.nginx-debian.html;
# 
#         server_name your_domain www.your_domain;
# 
#         location / {
#                 try_files $uri $uri/ =404;
#         }
# }

# sudo ln -s /etc/nginx/sites-available/your_domain /etc/nginx/sites-enabled/

# ----------------------------------------------
# TEST
# ----------------------------------------------
# sudo vim /etc/nginx/nginx.conf
# sudo nginx -t
# sudo systemctl restart nginx

# ----------------------------------------------
# LOGS
# ----------------------------------------------
# cat /var/log/nginx/access.log
# cat /var/log/nginx/error.log
