#!/bin/bash

path=/home/mrx/TFG/proyecto/LatencyQuality/sourceCode
executable=${path}/netPulse.py
date_Date=$(date "+%d-%m-%Y")
date_Time=$(date "+%H:%M:%S")
final_path=/home/mrx/TFG/proyecto/LatencyQuality/logs/${date_Date}.cron.log

echo -e "==========================================" >> $final_path
echo -e "Hora Inicio en formato UTC: ${date_Time}" >> $final_path
echo -e "\t[INFO] lanzando Script . . ." >> $final_path
$executable
echo -e "Hora Fin en formato UTC: ${date_Time}" >> $final_path
echo -e "\t[INFO] Proceso Finalizado" >> $final_path
